/*
 * This file is part of the AusStage RDF Vocabularies Package
 *
 * The AusStage RDF Vocabularies Package is free software: you can 
 * redistribute it and/or modify it under the terms of the GNU General 
 * Public License as published by the Free Software Foundation, either 
 * version 3 of the License, or (at your option) any later version.
 *
 * The AusStage RDF Vocabularies Package is distributed in the hope 
 * that it will be useful, but WITHOUT ANY WARRANTY; without even the 
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the AusStage RDF Vocabularies Package.  
 * If not, see <http://www.gnu.org/licenses/>.
*/

package au.edu.ausstage.vocabularies;
 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from http://motools.sf.net/event/event.n3 
 * @author Auto-generated by schemagen on 25 Jun 2010 09:03 
 */
public class Event {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/NET/c4dm/event.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Relates an event to an active agent (a person, a computer, ... :-) )</p> */
    public static final ObjectProperty agent = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#agent" );
    
    public static final ObjectProperty agent_in = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#agent_in" );
    
    /** <p>Relates an event to a passive factor (a tool, an instrument, an abstract cause...)</p> */
    public static final ObjectProperty factor = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#factor" );
    
    public static final ObjectProperty factor_of = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#factor_of" );
    
    public static final ObjectProperty hasAgent = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#hasAgent" );
    
    public static final ObjectProperty hasFactor = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#hasFactor" );
    
    public static final ObjectProperty hasProduct = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#hasProduct" );
    
    public static final ObjectProperty hasSubEvent = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#hasSubEvent" );
    
    public static final ObjectProperty isAgentIn = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#isAgentIn" );
    
    public static final ObjectProperty isFactorOf = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#isFactorOf" );
    
    /** <p>Relates an event to a spatial object.</p> */
    public static final ObjectProperty place = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#place" );
    
    public static final ObjectProperty producedIn = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#producedIn" );
    
    public static final ObjectProperty produced_in = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#produced_in" );
    
    /** <p>Relates an event to something produced during the event---a sound, a pie, 
     *  whatever...</p>
     */
    public static final ObjectProperty product = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#product" );
    
    /** <p>This property provides a way to split a complex event (for example, a performance 
     *  involving several musicians) into simpler ones (one event per musician).</p>
     */
    public static final ObjectProperty sub_event = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#sub_event" );
    
    /** <p>Relates an event to a time object, classifying a time region (either instantaneous 
     *  or having an extent). By using the Timeline ontology here, you can define 
     *  event happening on a recorded track or on any media with a temporal extent.</p>
     */
    public static final ObjectProperty time = m_model.createObjectProperty( "http://purl.org/NET/c4dm/event.owl#time" );
    
    public static final DatatypeProperty hasLiteralFactor = m_model.createDatatypeProperty( "http://purl.org/NET/c4dm/event.owl#hasLiteralFactor" );
    
    /** <p>Relates an event to a factor which can be described as a literal. This property 
     *  should not be used as-is, but should be subsumed by other, more specific, 
     *  properties (like an hypothetic :weatherCelsius, linking an event to a temperature).</p>
     */
    public static final DatatypeProperty literal_factor = m_model.createDatatypeProperty( "http://purl.org/NET/c4dm/event.owl#literal_factor" );
    
    /** <p>An arbitrary classification of a space/time region, by a cognitive agent. 
     *  An event may have actively participating agents, passive factors, products, 
     *  and a location in space/time.</p>
     */
    public static final OntClass Event = m_model.createClass( "http://purl.org/NET/c4dm/event.owl#Event" );
    
    /** <p>Everything used as a factor in an event</p> */
    public static final OntClass Factor = m_model.createClass( "http://purl.org/NET/c4dm/event.owl#Factor" );
    
    /** <p>Everything produced by an event</p> */
    public static final OntClass Product = m_model.createClass( "http://purl.org/NET/c4dm/event.owl#Product" );
    
}
